# Generated by Django 5.2.16 on 2026-08-03 06:25

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=20)),
                ('ip_address', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('failure_count', models.PositiveSmallIntegerField(default=0)),
                ('window_started_at', models.DateTimeField()),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_login_throttle',
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='accounts_user_email_ci_unique'),
        ),
        migrations.AddIndex(
            model_name='loginthrottle',
            index=models.Index(fields=['locked_until'], name='accounts_lo_locked__72afdc_idx'),
        ),
        migrations.AddConstraint(
            model_name='loginthrottle',
            constraint=models.UniqueConstraint(fields=('scope', 'ip_address', 'email'), name='accounts_login_throttle_identity_unique'),
        ),
    ]
