# Generated by Django 5.2.16 on 2026-08-03 08:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgePoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=80)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_points', to='curriculum.section')),
            ],
            options={
                'db_table': 'knowledge_point',
                'ordering': ('section', 'code'),
                'constraints': [models.UniqueConstraint(fields=('section', 'code'), name='knowledge_section_code_uq')],
            },
        ),
    ]
