# Generated by Django 5.2.16 on 2026-08-03 08:21

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_alter_subject_code_subject_subject_code_ci_uq'),
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='knowledgepoint',
            name='knowledge_section_code_uq',
        ),
        migrations.AddConstraint(
            model_name='knowledgepoint',
            constraint=models.UniqueConstraint(models.F('section'), django.db.models.functions.text.Lower('code'), name='knowledge_section_code_ci_uq'),
        ),
    ]
