# Generated by Django 5.2.16 on 2026-08-04 02:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_remove_knowledgepoint_knowledge_section_code_uq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgepoint',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='KnowledgeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('summary', models.TextField()),
                ('content_blocks', models.JSONField(default=list)),
                ('applicable_exam_edition', models.CharField(default='2025大纲/2026考试', max_length=80)),
                ('source_type', models.CharField(default='original_synthesis', max_length=80)),
                ('content_checksum', models.CharField(max_length=64)),
                ('review_status', models.CharField(choices=[('pending_review', '待审核'), ('reviewed', '已复核'), ('published', '已发布'), ('disputed', '有争议')], default='pending_review', max_length=24)),
                ('immutable_after_publish', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('knowledge_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='knowledge.knowledgepoint')),
            ],
            options={
                'db_table': 'knowledge_version',
                'ordering': ('knowledge_point', 'version_number'),
            },
        ),
        migrations.AddField(
            model_name='knowledgepoint',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_points', to='knowledge.knowledgeversion'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeversion',
            constraint=models.UniqueConstraint(fields=('knowledge_point', 'version_number'), name='knowledge_version_number_uq'),
        ),
    ]
