# Generated by Django 5.2.16 on 2026-08-03 08:11

import django.core.validators
import django.db.models.deletion
import provenance.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=255)),
                ('source_checksum', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('dry_run', '试运行'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败')], max_length=24)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('report', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'provenance_content_import_batch',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='SourceMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=160, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('source_type', models.CharField(max_length=80)),
                ('institution', models.CharField(blank=True, max_length=160)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rights_scope', models.CharField(max_length=80)),
                ('public_repo_allowed', models.BooleanField(default=False)),
                ('private_reference', models.CharField(blank=True, max_length=255, validators=[provenance.models._validate_private_reference])),
                ('extraction_method', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'provenance_source_material',
                'ordering': ('file_name',),
                'constraints': [models.CheckConstraint(condition=models.Q(('public_repo_allowed', True), ('rights_scope', 'private_personal_use'), _negated=True), name='private_source_not_public_ck')],
            },
        ),
        migrations.CreateModel(
            name='ContentImportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('created', '已创建'), ('versioned', '已创建版本'), ('skipped', '已跳过'), ('warning', '有警告'), ('error', '错误')], max_length=24)),
                ('action', models.CharField(max_length=40)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='provenance.contentimportbatch')),
            ],
            options={
                'db_table': 'provenance_content_import_item',
                'ordering': ('id',),
                'indexes': [models.Index(fields=['batch', 'status'], name='provenance__batch_i_8ff7db_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContentProvenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(max_length=80)),
                ('content_object_id', models.UUIDField()),
                ('source_page', models.PositiveIntegerField()),
                ('source_question_number', models.CharField(blank=True, max_length=80)),
                ('extraction_confidence', models.DecimalField(decimal_places=3, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('content_origin', models.CharField(max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('source_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_links', to='provenance.sourcematerial')),
            ],
            options={
                'db_table': 'provenance_content_provenance',
                'ordering': ('content_type', 'content_object_id', 'source_page'),
                'indexes': [models.Index(fields=['content_type', 'content_object_id'], name='provenance__content_bdea9a_idx'), models.Index(fields=['extraction_confidence'], name='provenance__extract_0c24ae_idx')],
            },
        ),
    ]
