# Generated by Django 5.2.16 on 2026-08-03 08:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=160, unique=True)),
                ('question_type', models.CharField(choices=[('single_choice', '单选题'), ('multiple_choice', '多选题')], max_length=24)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_review', '待审核'), ('published', '已发布'), ('disputed', '有争议'), ('obsolete', '已废止')], default='pending_review', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='curriculum.chapter')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='curriculum.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='curriculum.subject')),
            ],
            options={
                'db_table': 'questions_question',
                'ordering': ('external_id',),
            },
        ),
        migrations.CreateModel(
            name='QuestionVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('stem', models.TextField()),
                ('answer_schema', models.JSONField(default=dict)),
                ('canonical_answer', models.JSONField(default=list)),
                ('presented_option_order', models.JSONField(default=list)),
                ('source_answer', models.JSONField(default=list)),
                ('analysis', models.TextField(blank=True)),
                ('difficulty', models.CharField(blank=True, max_length=24)),
                ('content_checksum', models.CharField(max_length=64)),
                ('source_type', models.CharField(max_length=80)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('applicable_exam_edition', models.CharField(blank=True, max_length=80)),
                ('review_status', models.CharField(choices=[('pending_review', '待审核'), ('reviewed', '已复核'), ('disputed', '有争议'), ('published', '已发布')], default='pending_review', max_length=24)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('immutable_after_publish', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='questions.question')),
            ],
            options={
                'db_table': 'questions_question_version',
                'ordering': ('question', 'version_number'),
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=12)),
                ('text', models.TextField()),
                ('sort_order', models.PositiveSmallIntegerField()),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='options', to='questions.questionversion')),
            ],
            options={
                'db_table': 'questions_question_option',
                'ordering': ('question_version', 'sort_order'),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_questions', to='questions.questionversion'),
        ),
        migrations.AddIndex(
            model_name='questionversion',
            index=models.Index(fields=['review_status', 'source_type'], name='questions_q_review__589600_idx'),
        ),
        migrations.AddIndex(
            model_name='questionversion',
            index=models.Index(fields=['content_checksum'], name='questions_q_content_94b972_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionversion',
            constraint=models.UniqueConstraint(fields=('question', 'version_number'), name='question_version_number_uq'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(fields=('question_version', 'label'), name='question_option_label_uq'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(fields=('question_version', 'sort_order'), name='question_option_order_uq'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['subject', 'chapter', 'section'], name='questions_q_subject_e2d713_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['status', 'question_type'], name='questions_q_status_199417_idx'),
        ),
    ]
