# Generated by Django 5.2.16 on 2026-08-03 08:21

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_alter_subject_code_subject_subject_code_ci_uq'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='external_id',
            field=models.CharField(max_length=160),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('external_id'), name='question_external_id_ci_uq'),
        ),
    ]
