# Generated by Django 5.2.16 on 2026-08-03 08:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'curriculum_subject',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=160)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chapters', to='curriculum.subject')),
            ],
            options={
                'db_table': 'curriculum_chapter',
                'ordering': ('subject', 'number'),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=180)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='curriculum.chapter')),
            ],
            options={
                'db_table': 'curriculum_section',
                'ordering': ('chapter', 'number'),
                'constraints': [models.UniqueConstraint(fields=('chapter', 'number'), name='section_chapter_number_uq')],
            },
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('subject', 'number'), name='chapter_subject_number_uq'),
        ),
    ]
