# Generated by Django 5.2.16 on 2026-08-04 02:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0002_alter_question_external_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_answer', models.JSONField(default=list)),
                ('is_correct', models.BooleanField()),
                ('elapsed_seconds', models.PositiveIntegerField(default=0)),
                ('wrong_reason', models.CharField(blank=True, choices=[('', '未选择'), ('concept', '概念不清'), ('confusion', '选项混淆'), ('calculation', '计算失误'), ('reading', '审题失误'), ('memory', '记忆不牢')], default='', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_attempts', to='questions.questionversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practice_answer_attempt',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'created_at'], name='practice_an_user_id_52aeb0_idx'), models.Index(fields=['user', 'is_correct'], name='practice_an_user_id_8eb440_idx')],
            },
        ),
        migrations.CreateModel(
            name='WrongQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wrong_count', models.PositiveIntegerField(default=1)),
                ('correct_streak', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', '待复习'), ('mastered', '已掌握')], default='active', max_length=16)),
                ('next_review_at', models.DateTimeField()),
                ('last_attempt_at', models.DateTimeField()),
                ('last_wrong_reason', models.CharField(blank=True, max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wrong_records', to='questions.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wrong_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practice_wrong_question',
                'ordering': ('next_review_at', '-wrong_count'),
                'indexes': [models.Index(fields=['user', 'status', 'next_review_at'], name='practice_wr_user_id_d16aee_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'question'), name='wrong_question_user_question_uq')],
            },
        ),
    ]
