# Generated by Django 5.2.16 on 2026-08-04 04:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_alter_subject_code_subject_subject_code_ci_uq'),
        ('practice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('started', '学习中'), ('completed', '已完成')], default='started', max_length=16)),
                ('first_opened_at', models.DateTimeField(auto_now_add=True)),
                ('last_opened_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learner_progress', to='curriculum.section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practice_section_progress',
                'indexes': [models.Index(fields=['user', 'status', 'last_opened_at'], name='practice_se_user_id_f02542_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'section'), name='section_progress_user_section_uq')],
            },
        ),
    ]
